### ISSUE TITLE
Building of vmaf not working

### ISSUE THREAD

**Issue by BlackScreen** [m-ab-s/media-autobuild_suite#1466]
```
12:24:09   Running git clone for vmaf...
12:24:29 ┌ vmaf git  ................................. [Recently updated]
12:24:29 ├ Running clean...
12:24:29 ├ Running make...
Likely error (tail of the failed operation logfile):
ninja: Entering directory `.'
[1/2] g++ @tools/vmafossexec.exe.rsp
FAILED: tools/vmafossexec.exe
g++ @tools/vmafossexec.exe.rsp
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/libgcc_eh.a(unwind-seh.o):(.text+0x3d0): multiple definition of `_Unwind_Resume'; src/libvmaf.dll.a(d000018.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
[2/2] "C:/Development/MABS/msys64/mingw64/bin/meson" "--internal" "vcstagger" "../include/vcs_version.h.in" "include/vcs_version.h" "1.3.16" "C:/Development/MABS/build/vmaf-git/libvmaf/include" "@VCS_TAG@" "(.*)" "C:/Development/MABS/msys64/usr/bin/git.EXE" "--git-dir" "C:/Development/MABS/build/vmaf-git/libvmaf/../.git" "describe" "--tags" "--long" "--match" "?.*.*" "--always"
fatal: Not a valid object name .ninja_log
ninja: build stopped: subcommand failed.
make: *** [Makefile:3: all] Error 1
make failed. Check C:/Development/MABS/build/vmaf-git/ab-suite.make.log
This is required for other packages, so this script will exit.
12:24:38   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zg03.zip
Copy and paste [logs.zip](https://0x0.st/zg03.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by 1480c1** [comment]
They changed to meson recently

**Comment by BlackScreen** [comment]
> They changed to meson recently

Ok, anything I can do? Or do you have to change something in the suite and then commit it?

**Comment by 1480c1** [comment]
I'm looking into possible fixes

**Comment by BlackScreen** [comment]
> I'm looking into possible fixes

Ok, thank you! :)

**Comment by GyanD** [comment]
Tether to commit `d4d48dd` of VMAF.

**Comment by ImportTaste** [comment]
Here is a temporary solution. It hard resets vmaf-git to `d4d48dd` until this issue (i.e. the issue I am posting this on) is closed. Just paste into mintty.

```
echo '#!/bin/bash

_pre_make() {
    if [ `curl -s https://api.github.com/repos/m-ab-s/media-autobuild_suite/issues/1466 | jq -r ".state"` == open ]
    then
        git reset --hard d4d48dd
    else
        rm -f /trunk/build/vmaf_extra.sh
    fi
}'>/trunk/build/vmaf_extra.sh
```

**Comment by Helenerineium** [comment]
Here's my patch for vmaf: [vmaf.txt](https://github.com/m-ab-s/media-autobuild_suite/files/3829450/vmaf.txt) (Save as .diff or .patch after download)
It address three things:
1. install headers in `include/` ( was `include/libvmaf/` )
2. build static library only
3. install `libvmaf.pc` ( was `vmaf.pc` )

You can use it like this
```
_check=(libvmaf.{a,h,pc})
if [[ $ffmpeg != "no" ]] && enabled libvmaf &&
    do_vcs "https://github.com/Netflix/vmaf.git"; then
    do_uninstall share/model "${_check[@]}"
    log clean make clean
    patch -sp1 -i <path_to_patch>
    cd_safe libvmaf
    do_mesoninstall
    grep_or_sed stdc++ "$MINGW_PREFIX"/lib/pkgconfig/libvmaf.pc 's/-lpthread/& -lstdc++/'
    do_checkIfExist
fi
```

**Comment by 1480c1** [comment]
@Helenerineium are you going to open a PR for it, or do you want me to add it?

**Comment by wiiaboo** [comment]
The header and pkgconfig file changes are perfectly replaceable by a `cp` or `do_install` instead.

**Comment by wiiaboo** [comment]
And `do_meson` already sets ` --default-library=static`, so is the other remaining change really needed?

**Comment by wiiaboo** [comment]
If it is, then this is an upstream issue and it should be fixed there, not just here.

**Comment by wiiaboo** [comment]
I think there's already a fix submitted to upstream related to this.

**Comment by Selur** [comment]
current script fails:  [logs.zip](https://0x0.st/z6Bb.zip)

**Comment by BlackScreen** [comment]
Problem still persists. :(

**Comment by subz390** [comment]
What's the state of this fix  @1480c1  - this is the first time I'm using media-autobuild_suite and the initial build process has stopped with no obvious way, to me anyway, of how to proceed.  What am I waiting for here?  because right now the suite is 100% broken, it just doesn't work.
How do I get it working?
It looks like @Helenerineium posted a fix to this issue 13 days ago but I downloaded media-autobuild_suite yesterday so hasn't that fix been applied yet?
Like I said the media-autobuild_suite is 100% broken for me because of this and I'd love to get the initial build process going again.
Many thanks

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/pull/1480

That should fix it.

Depending on how you downloaded the suite, you can either run
```bash
git fetch origin pull/1480/head
git checkout FETCH_HEAD
```

and run the batch script, or go [here](https://github.com/1480c1/media-autobuild_suite/blob/vmaf/build/media-suite_compile.sh) and download only the script into your build folder

**Comment by subz390** [comment]
Confirming your edit fixed the error.

**Comment by chrno74** [comment]
Sorry, I'm still not able to complete the build. The error itself has gone after applying [#1480](https://github.com/m-ab-s/media-autobuild_suite/pull/1480), but now I get this one:

```
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
Installing clang... done
├ Compiling static FFmpeg...
├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib`
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-schannel --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --disable-debug --enable-libzimg --enable-version3 --enable-libfdk-aac --enable-libvmaf --enable-opencl --extra-libs=-liconv --disable-w32threads --enable-gpl --enable-nonfree
ERROR: libvmaf >= 1.3.9 not found using pkg-config
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/3884286/logs.zip)

**Comment by 1480c1** [comment]
Try deleting `local64/lib/libvmaf.a` and rerunning and pasting the error, your `config.log` has a lot of weird undefined errors

**Comment by chrno74** [comment]
Thanks for your immediate reply. Done as described, but the error and the log stays all the same (really long error list at the end of config.log). I can only guess, but I think this my problem: [https://patchwork.ffmpeg.org/patch/16221/](https://patchwork.ffmpeg.org/patch/16221/). For I have already removed the installed vmaf this may double the trouble... No idea, how to move on and get this fixed in my personal environment. Wondering if starting from the scratch may be of any help.

**Comment by chrno74** [comment]
Killed complete media autobuild suite, downloaded new, creation started without any old trash being around. Still no change...

```
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-schannel --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libx264 --enable-libx265 --disable-debug --enable-libzimg --enable-version3 --enable-libfdk-aac --enable-libvmaf --extra-libs=-liconv --disable-w32threads --enable-gpl --enable-nonfree
ERROR: libvmaf >= 1.3.9 not found using pkg-config
```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/3889217/logs.zip)

Turning off --enable-libvmaf option and compiling is finishing without any problems. Any help is welcome.

**Comment by 1480c1** [comment]
Will try to see what's wrong after fixing openssl and libxml2 problems in another issue
