### ISSUE TITLE
Error running configure when  running git update for curl

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2281]
``` 20:21:03   Running git update for curl...
20:22:18 ┌ curl git  .................................... [Updates found]
20:22:20 ├ Running uninstall...
20:22:20 ├ Running autogen...
20:23:02 ├ Running configure...
Likely error (tail of the failed operation logfile):
  --with-bearssl
  --with-gnutls
  --with-mbedtls
  --with-nss
  --with-openssl (also works for BoringSSL and libressl)
  --with-rustls
  --with-schannel
  --with-secure-transport
  --with-wolfssl

configure failed. Check C:/MinGW-w64/build/curl-git/build-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
20:23:10   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ofvQ.zip
Copy and paste [logs.zip](https://0x0.st/ofvQ.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/ofvQ.zip)
[ab-suite.configure.log](https://github.com/m-ab-s/media-autobuild_suite/files/9535370/ab-suite.configure.log)

**Comment by don05837** [comment]
I undid the last change, ie: https://github.com/m-ab-s/media-autobuild_suite/commit/7c541d426c01ff80f716990b8fb092f0cfcb8d81
and it compiled past the curl. The rest is still compiling so I'll have to wait and see if it works. I'm not sure why those changes were made maybe somebody with more experience can comment.

**Comment by kliffgomel** [comment]
I have already raised this issue https://github.com/m-ab-s/media-autobuild_suite/issues/2278. For myself, I solved this problem by replacing the curl=1 parameter with curl=4 in the media-autobuild_suite.ini configuration file.

**Comment by 1480c1** [comment]
Should be fixed by https://github.com/m-ab-s/media-autobuild_suite/commit/896e1ca1ed1163fe55b36d31a036ec8e15f29874

**Comment by RivenSkaye** [comment]
This is unfortunately not yet fixed.  [logs.zip](https://0x0.st/oJX2.zip), at least with `curl=6` (LibreSSL).
Setting `curl=5` works just fine, so it _seems_ to be a Libre-only issue?
