### ISSUE TITLE
[mingw64] [xavs2] [clang] encoder.c:2150:60: error: incompatible function pointer type passed

### ISSUE THREAD

**Issue by snowbie** [m-ab-s/media-autobuild_suite#2417]
``` bash
  Running git update for xavs2...
┌ xavs2 git  .......................................... [Recently updated]
├ Running uninstall...
├ Running configure...
├ Running install...
Likely error (tail of the failed operation logfile):
void  xavs2_threadpool_run   (xavs2_threadpool_t *pool, void *(*func)(void *), void *arg, int wait_sign);
                                                                ^
C:/mabs/build/xavs2-git/source/encoder/encoder.c:2150:60: error: incompatible function pointer types passing 'void *(xavs2_t *)' (aka 'void *(struct xavs2_t *)') to parameter of type 'void *(*)(void *)' [-Wincompatible-function-pointer-types]
            xavs2_threadpool_run(h->h_top->threadpool_aec, encoder_aec_encode_one_frame, h, 0);
                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/mabs/build/xavs2-git/source/common/threadpool.h:46:65: note: passing argument to parameter 'func' here
void  xavs2_threadpool_run   (xavs2_threadpool_t *pool, void *(*func)(void *), void *arg, int wait_sign);
                                                                ^
4 warnings and 2 errors generated.
make: *** [Makefile:266: encoder/encoder.o] Error 1
install failed. Check C:/mabs/build/xavs2-git/build/linux/ab-suite.install.log
This is required for other packages, so this script will exit.

```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11223880/logs.zip)

**Comment by Biswa96** [comment]
This https://github.com/m-ab-s/media-autobuild_suite/commit/5782d728eb1d9b524c46155337b3d2b61dcb261d commit should fix the issue. Please try to rebuild.

**Comment by snowbie** [comment]
``` bash
┌ xavs2 git  .......................................... [Recently updated]
├ Running uninstall...
├ Running configure...
├ Running install...
Likely error (tail of the failed operation logfile):
void  xavs2_threadpool_run   (xavs2_threadpool_t *pool, void *(*func)(void *), void *arg, int wait_sign);
                                                                ^
C:/mabs/build/xavs2-git/source/encoder/encoder.c:2150:60: error: incompatible function pointer types passing 'void *(xavs2_t *)' (aka 'void *(struct xavs2_t *)') to parameter of type 'void *(*)(void *)' [-Wincompatible-function-pointer-types]
            xavs2_threadpool_run(h->h_top->threadpool_aec, encoder_aec_encode_one_frame, h, 0);
                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/mabs/build/xavs2-git/source/common/threadpool.h:46:65: note: passing argument to parameter 'func' here
void  xavs2_threadpool_run   (xavs2_threadpool_t *pool, void *(*func)(void *), void *arg, int wait_sign);
                                                                ^
4 warnings and 2 errors generated.
make: *** [Makefile:266: encoder/encoder.o] Error 1
install failed. Check C:/mabs/build/xavs2-git/build/linux/ab-suite.install.log
This is required for other packages, so this script will exit.

```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11239560/logs.zip)

Still occurring after clearing cache, deleting build folder, and rebuilding.

**Comment by Biswa96** [comment]
Did you update this repository with `git pull` command?

**Comment by snowbie** [comment]
Yep. I just checked media-suite_compile.sh to see if the patch was included, and ran mabs again just to be safe. Same error.

**Comment by Biswa96** [comment]
It seems that @1480c1 applied the patch to xavs instead of xavs2. Oops!

**Comment by snowbie** [comment]
On the bright side, the patch does indeed work when applied to xavs2 :^)
